module.exports = {
    // Bank Management
    CREATE_BANK: "CREATE_BANK",
    VIEW_ALL_BANKS: "VIEW_ALL_BANKS",
    VIEW_BANK_DETAILS: "VIEW_BANK_DETAILS",
    UPDATE_BANK_STATUS: "UPDATE_BANK_STATUS", // Suspend/Activate
    DELETE_BANK: "DELETE_BANK", // Soft delete
    MANAGE_BANK_SUBSCRIPTION: "MANAGE_BANK_SUBSCRIPTION",

    // Branch Management
    CREATE_BRANCH: "CREATE_BRANCH",
    VIEW_ALL_BRANCHES: "VIEW_ALL_BRANCHES",
    VIEW_BRANCH_DETAILS: "VIEW_BRANCH_DETAILS",
    UPDATE_BRANCH: "UPDATE_BRANCH",
    DELETE_BRANCH: "DELETE_BRANCH",

    // User/Staff Management
    CREATE_USER: "CREATE_USER", // Bank Admin creates Branch Manager/Employee
    VIEW_ALL_USERS: "VIEW_ALL_USERS",
    UPDATE_USER_STATUS: "UPDATE_USER_STATUS",

    // Customer Management
    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    VIEW_ALL_CUSTOMERS: "VIEW_ALL_CUSTOMERS",
    VIEW_CUSTOMER_DETAILS: "VIEW_CUSTOMER_DETAILS",
    UPDATE_CUSTOMER: "UPDATE_CUSTOMER",

    // Loan Management
    CREATE_LOAN: "CREATE_LOAN",
    VIEW_ALL_LOANS: "VIEW_ALL_LOANS",
    VIEW_LOAN_DETAILS: "VIEW_LOAN_DETAILS",
    Request_LOAN_APPROVAL: "Request_LOAN_APPROVAL",
    APPROVE_LOAN: "APPROVE_LOAN",
    REJECT_LOAN: "REJECT_LOAN",

    // EMI & Payments
    VIEW_EMI: "VIEW_EMI",
    COLLECT_EMI: "COLLECT_EMI", // Make payment

    // Reports & Dashboard
    VIEW_PLATFORM_DASHBOARD: "VIEW_PLATFORM_DASHBOARD", // Super Admin
    VIEW_BANK_REPORTS: "VIEW_BANK_REPORTS", // Bank Admin
    VIEW_BRANCH_REPORTS: "VIEW_BRANCH_REPORTS", // Branch Manager
    VIEW_OWN_REPORTS: "VIEW_OWN_REPORTS", // Employee/Customer

    // Self
    VIEW_PROFILE: "VIEW_PROFILE",
    UPDATE_PROFILE: "UPDATE_PROFILE",
};
