module.exports = {
    CREATE_BANK: "CREATE_BANK",
    VIEW_BANK: "VIEW_BANK",
    SUSPEND_BANK: "SUSPEND_BANK",

    CREATE_BRANCH: "CREATE_BRANCH",
    VIEW_BRANCH: "VIEW_BRANCH",

    CREATE_USER: "CREATE_USER",
    VIEW_USER: "VIEW_USER",

    CREATE_CUSTOMER: "CREATE_CUSTOMER",
    VIEW_CUSTOMER: "VIEW_CUSTOMER",

    CREATE_LOAN: "CREATE_LOAN",
    APPROVE_LOAN: "APPROVE_LOAN",
    VIEW_LOAN: "VIEW_LOAN",

    COLLECT_EMI: "COLLECT_EMI",
    VIEW_REPORTS: "VIEW_REPORTS",
};
