module.exports = {
  // Platform & Bank Management
  CREATE_BANK: "CREATE_BANK",
  VIEW_BANK: "VIEW_BANK",
  SUSPEND_BANK: "SUSPEND_BANK",

  CREATE_BRANCH: "CREATE_BRANCH",
  VIEW_BRANCH: "VIEW_BRANCH",
  UPDATE_BRANCH: "UPDATE_BRANCH",

  // User & Access Control
  CREATE_USER: "CREATE_USER",
  VIEW_USER: "VIEW_USER",
  MANAGE_ROLES: "MANAGE_ROLES",
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",

  // Customer Management
  CREATE_CUSTOMER: "CREATE_CUSTOMER",
  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",

  // Loan Management
  CREATE_LOAN: "CREATE_LOAN",
  APPROVE_LOAN: "APPROVE_LOAN",
  VIEW_LOAN: "VIEW_LOAN",
  DISBURSE_LOAN: "DISBURSE_LOAN",
  COLLECT_EMI: "COLLECT_EMI",
  CLOSE_LOAN: "CLOSE_LOAN",

  // Producer Company Modules
  MANAGE_PRODUCER_MEMBERS: "MANAGE_PRODUCER_MEMBERS",
  MANAGE_SHARE_CAPITAL: "MANAGE_SHARE_CAPITAL",
  MANAGE_DEPOSITS: "MANAGE_DEPOSITS",
  MANAGE_INSURANCE: "MANAGE_INSURANCE",
  PRODUCER_CASH_OPERATIONS: "PRODUCER_CASH_OPERATIONS",

  // Accounting & Finance
  MANAGE_ACCOUNTS: "MANAGE_ACCOUNTS",
  MANAGE_VOUCHERS: "MANAGE_VOUCHERS",
  VIEW_LEDGER: "VIEW_LEDGER",
  MANAGE_CHEQUES: "MANAGE_CHEQUES",

  // Reporting & Analytics
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_ANALYTICS: "VIEW_ANALYTICS",
  VIEW_MIS_REPORTS: "VIEW_MIS_REPORTS",
};
